### ISSUE TITLE
wlroots version requierement.

### ISSUE THREAD

**Issue by ahmadraniri** [kcirick/simplewc#2]
Hello, nice project  @kcirick ! I'm looking for layer_shell example implementation and found your compositor. BTW, which version of wlroots your project is based on ? Would be good if you add it to the README.

**Comment by kcirick** [comment]
Thank you. It is based on wlroots 0.17. There were quite a number of changes from 0.16 -> 0.17. You are completely right and I should indicate this to the README.

**Comment by kcirick** [comment]
Updated README.

Closing
