### ISSUE TITLE
spawn foot causing compositor freeze.

### ISSUE THREAD

**Issue by lidgnulinux** [kcirick/simplewc#4]
Hello, I run this compositor from tty and everytime I want to spawn foot via keybind / shortcut, the compositor will freeze. The keyboard also goes unresponsive, I need to login to ssh and kill the compositor from there.

**Comment by kcirick** [comment]
Thank you for the reporting. Does it freeze when you spawn foot via "swc --start foot"? or only when you use it via keybind? This will direct me whether the problem is with spawn function (in main.c) or something to do with keybind.

**Comment by lidgnulinux** [comment]
Hello, I'm sorry for long respond. When I spawn it via `swc --start foot`, it's not freeze but foot take a long time to show. It's only freeze when it's spawned via keybind. Just for note, I also try to spawn other programs via keybind and swc also freeze.

**Comment by lidgnulinux** [comment]
Not interested on this anymore. Close it.
